CRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sale/', include('sale.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^teacher/', include('teacher.urls')),
    url(r'^kevin-admin/', include('KevinAdmin.urls')),
    url(r'^login/', views.acc_login),
    url(r'^logout/', views.acc_logout, name="logout"),
]

student/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as vs

urlpatterns = [
    url(r'^$', vs.student_index, name='student_index'),
    url(r'^my-courses/$', vs.my_courses, name='my_courses'),
    url(r'^my-class/$', vs.my_class, name='my_class'),
    url(r'^homework-manage/(?P<class_id>(\d+))/$', vs.homework_manage, name='homework_manage'),
    url(r'^upload-homework/(?P<study_record_id>(\d+))/$', vs.homework_upload, name='homework_upload'),
    url(r'^upload-homework/(?P<study_record_id>(\d+))/upload_file$', vs.homework_file_upload,
        name='homework_file_upload'),
]

database/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)


class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_superuser = True
        user.save(using=self._db)
        return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,

    )
    name = models.CharField(max_length=64, verbose_name="姓名")
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    role = models.ManyToManyField("Role", blank=True, null=True)
    customer = models.OneToOneField('CustomerInfo', blank=True, null=True)
    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):  # __unicode__ on Python 2
        return self.email

    class Meta:
        permissions = (
            ('database_table_list', '可以查看kevinadmin每张表里所有的数据'),
            ('database_table_list_view', '可以访问kevinadmin表里每条数据的修改页'),
            ('database_table_list_change', '可以对kevinadmin表里的每条数据进行修改'),
            ('database_table_obj_add_view', '可以访问kevinadmin每张表的数据增加页'),
            ('database_table_obj_add', '可以对kevinadmin每张表进行数据添加'),
            ('database_table_obj_delete', '可以对kevinadmin每张表进行数据删除'),
            ('database_table_obj_delete_view', '可以对kevinadmin删除时查看所关联的数据'),
             )

        #
        # class UserProfile(models.Model):
        #     """用户信息表"""
        #     user = models.OneToOneField(User)
        #     name = models.CharField(max_length=64, verbose_name="姓名")
        #     role = models.ManyToManyField('Role', blank=True)
        #     customer = models.OneToOneField('CustomerInfo', null=True, blank=True)
        #
        #     def __str__(self):
        #         return self.name


class Role(models.Model):
    """角色表"""
    name = models.CharField(max_length=64, unique=True)
    menus = models.ManyToManyField('Menus')

    def __str__(self):
        return self.name


class CustomerInfo(models.Model):
    """客户信息表"""
    name = models.CharField(max_length=64, default=None)
    contact_type_choices = {
        (0, 'qq'),
        (1, '微信'),
        (2, '手机'),
    }
    contact_type = models.SmallIntegerField(choices=contact_type_choices)
    contact = models.CharField(max_length=64, unique=True)
    source_choices = {
        (0, 'QQ群'),
        (1, '51CTO'),
        (2, '百度推广'),
        (3, '知乎'),
        (4, '转介绍'),
        (5, '其他')
    }
    source = models.SmallIntegerField(choices=source_choices)
    referral_from = models.ForeignKey('self', blank=True, null=True)
    consult_courses = models.ManyToManyField('Course', verbose_name='咨询课程')
    consult_content = models.TextField(verbose_name='咨询描述')
    consultant = models.ForeignKey('UserProfile', verbose_name='课程顾问')
    status_choices = {
        (0, '未报名'),
        (1, '已报名'),
        (2, '已退学')
    }
    id_num = models.CharField(max_length=128, null=True, blank=True)
    emergency_contact = models.PositiveIntegerField(blank=True, null=True)
    status = models.SmallIntegerField(choices=status_choices)
    gender_choices = {(0, '男'), (1, ' 女')}
    gender = models.PositiveIntegerField(blank=True, null=True, choices=gender_choices)
    date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = '客户信息'

    def __str__(self):
        return self.name


class Student(models.Model):
    """学员表"""
    customer = models.OneToOneField("CustomerInfo")
    class_grade = models.ManyToManyField('ClassList')

    def __str__(self):
        return '%s' % self.customer


class CustomerFollowRecord(models.Model):
    """客户跟踪记录表"""
    customer = models.ForeignKey('CustomerInfo')
    content = models.TextField(verbose_name='跟踪内容')
    user = models.ForeignKey('UserProfile', verbose_name='跟进人')
    status_choices = {
        (0, '近期无报名计划'),
        (1, '一个月内报名'),
        (2, '两周内报名'),
        (3, '已报名'),
    }
    status = models.SmallIntegerField(choices=status_choices)
    data = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.content


class Course(models.Model):
    """课程表"""
    name = models.CharField(max_length=64, verbose_name='课程名称', unique=True)
    price = models.PositiveSmallIntegerField()
    period = models.PositiveSmallIntegerField(verbose_name='课程周期(月)', default=5)
    outline = models.TextField(verbose_name='课程大纲')

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """班级列表"""
    branch = models.ForeignKey('Branch')
    course = models.ForeignKey('Course')
    class_type_choices = {
        (0, '脱产'),
        (1, '周末'),
        (2, '网络班'),
    }
    class_type = models.SmallIntegerField(choices=class_type_choices, default=0)
    semester = models.SmallIntegerField(verbose_name='学期')
    contract_template = models.ForeignKey('ContractTemplate', blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name='讲师')
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField('毕业日期', blank=True, null=True)

    class Meta:
        unique_together = ('branch', 'course', 'semester', 'class_type')

    def __str__(self):
        return "{0}({1})".format(self.course.name, self.semester)


class CourseRecord(models.Model):
    """上课记录"""
    class_grade = models.ForeignKey('ClassList', verbose_name='上课班级')
    day_num = models.PositiveSmallIntegerField(verbose_name='课程节次')
    teacher = models.ForeignKey('UserProfile')
    title = models.CharField(max_length=64, verbose_name='本节主题')
    content = models.TextField('本节内容')
    has_homework = models.BooleanField('本节有作业', default=True)
    homework = models.TextField('作业需求', blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('class_grade', 'day_num')

    def __str__(self):
        return "{0}第{1}节".format(self.class_grade, self.day_num)


class StudyRecord(models.Model):
    """学习记录表"""
    course_record = models.ForeignKey('CourseRecord')
    student = models.ForeignKey('Student')
    score_choices = {
        (100, "A+"),
        (90, "A"),
        (85, "B+"),
        (80, "B"),
        (75, "B-"),
        (70, "C+"),
        (60, "C"),
        (40, "C-"),
        (-50, "D"),
        (0, "N/A"),
        (-100, "COPY"),
    }
    score = models.SmallIntegerField(choices=score_choices, default=0)
    show_choices = {
        (0, '缺勤'),
        (1, '已到'),
        (2, '迟到'),
        (3, '早退'),
    }
    show_status = models.SmallIntegerField(choices=show_choices)
    note = models.CharField("成绩备注", blank=True, null=True, max_length=1024)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('course_record', 'student')

    def __str__(self):
        return "{0} {1} {2}".format(self.course_record, self.student, self.score)


class Branch(models.Model):
    """校区"""
    name = models.CharField(max_length=64, unique=True)
    addr = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Menus(models.Model):
    """动态菜单"""
    name = models.CharField(max_length=64)
    url_type_choices = {
        (0, 'absolute'),
        (1, 'dynamic'),
    }
    url_type = models.SmallIntegerField(choices=url_type_choices, default=0)
    url_name = models.CharField(max_length=128)

    class Meta:
        unique_together = ('name', 'url_name')

    def __str__(self):
        return self.name


class ContractTemplate(models.Model):
    """存储合同模板"""
    name = models.CharField(max_length=64)
    content = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.name


class StudentEnrollment(models.Model):
    """学员报名表"""
    customer = models.ForeignKey('CustomerInfo')
    class_grade = models.ForeignKey('ClassList')
    consultant = models.ForeignKey('UserProfile')
    contract_agree = models.BooleanField(default=False)
    contract_signed_date = models.DateTimeField(blank=True, null=True)
    contract_approved = models.BooleanField(default=False)
    contract_approved_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        unique_together = ('customer', 'class_grade')

    def __str__(self):
        return '%s' % self.customer


class PaymentRecord(models.Model):
    """缴费记录表"""
    enrollment = models.ForeignKey('StudentEnrollment')
    payment_type_choices = {
        (0, '报名费'),
        (1, '学费'),
        (2, '退费'),
    }
    payment_type = models.SmallIntegerField(choices=payment_type_choices)
    amount = models.IntegerField('所缴费用', default=500)
    consultant = models.ForeignKey('UserProfile')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.enrollment

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render, redirect, HttpResponse
from database.models import *
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json
import os
from django.conf import settings


def student_index(request):
    return redirect('/student/my-courses/')


@login_required()
def my_courses(request):
    customer = request.user.customer
    if customer:
        student = Student.objects.get(customer=customer)
        class_list = ClassList.objects.filter(student=student)
    return render(request, 'student/my_courses.html', locals())


@login_required()
def my_class(request):
    customer = request.user.customer
    if customer:
        student = Student.objects.get(customer=customer)
        class_list = ClassList.objects.filter(student=student)
        students_list = {}
        for classes in class_list:
            students = Student.objects.filter(class_grade=classes)
            students_list[classes] = students
    else:
        return HttpResponse('你还不是学生')
    return render(request, 'student/my_class.html', locals())


@login_required()
def homework_manage(request, class_id):
    customer = request.user.customer
    if customer:
        student = Student.objects.get(customer=customer)
        class_grade = ClassList.objects.get(id=class_id)
        study_record_list = StudyRecord.objects.filter(student=student, course_record__class_grade=class_grade)
    else:
        return HttpResponse('你还不是学生')
    return render(request, 'student/homework_manage.html', locals())


@login_required()
def homework_upload(request, study_record_id):
    course_record = CourseRecord.objects.get(studyrecord=study_record_id)
    customer = request.user.customer
    student = Student.objects.get(customer=customer)
    uploaded_files = []
    study_record_upload_dir = os.path.join(settings.STUDENT_FILE_HOMEWORK, str(course_record))
    student_upload_dir = os.path.join(study_record_upload_dir, str(student.customer.name))
    if not os.path.isdir(study_record_upload_dir):
        os.mkdir(study_record_upload_dir)
    if os.path.isdir(student_upload_dir):
        uploaded_files = os.listdir(student_upload_dir)

    return render(request, 'student/homework_upload.html', locals())


@csrf_exempt
def homework_file_upload(request, study_record_id):
    customer = request.user.customer
    student = Student.objects.get(customer=customer)
    course_record = CourseRecord.objects.get(studyrecord=study_record_id)
    study_record_upload_dir = os.path.join(settings.STUDENT_FILE_HOMEWORK, str(course_record))
    student_upload_dir = os.path.join(study_record_upload_dir, str(student.customer.name))
    if not os.path.isdir(student_upload_dir):
        os.makedirs(student_upload_dir)
    file_obj = request.FILES.get('file')
    if len(os.listdir(student_upload_dir)) <= 4:
        with open(os.path.join(student_upload_dir, file_obj.name), 'wb') as f:
            for chunk in file_obj.chunks():
                f.write(chunk)
    else:
        return HttpResponse(json.dumps({'status': False, 'message': 'max upload limit is four'}))
    return HttpResponse(json.dumps({'status': True}))

templates/student/homework_manage.html
{% extends 'index.html' %}
{% block css %}
    <style>
        .study-record span{
            font-size: 20px;
        }
    </style>
{% endblock %}
{% block table_content %}
    <h1 class="page-header">作业管理</h1>
    <div class="container study-record">
    <ol class="breadcrumb">
            <li><a href="{% url 'my_courses' %}">我的课程</a></li>
            <li class="active">作业管理</li>
        </ol>
    <span style="color:indianred;">我的课程[{{ class_grade }}]</span>

        <span  style="color: indianred;" class="pull-right">学习记录</span>
        <hr>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>日期</th>
                <th>节次</th>
                <th>本节讲师</th>
                <th>上课记录</th>
                <th>本节成绩</th>
                <th>作业内容</th>
                <th>我的作业</th>
            </tr>
        </thead>
    <tbody>
        {% for study_record in study_record_list %}
            <tr>
                <td>{{ study_record.date | date }}</td>
                <td>{{ study_record.course_record.day_num}}</td>
                <td>{{ study_record.course_record.teacher }}</td>
                <td>{{ study_record.get_show_status_display }}</td>
                <td>{{ study_record.get_score_display }}</td>
                {% if study_record.course_record.has_homework %}
                    <td>{{ study_record.course_record.homework }}</td>
                    <td><a href="/student/upload-homework/{{ study_record.id }}">交作业</a></td>
                    {% else %}
                    <td> 没有作业</td>
                    <td> </td>
                {% endif %}


            </tr>
        {% endfor %}

    </tbody>
    </table>
    </div>
{% endblock %}

templates/student/homework_upload.html
{% extends 'index.html' %}
{% block css %}
    <style>
        .study-record span {
            font-size: 20px;
        }
    </style>
{% endblock %}
{% block table_content %}
    <h1 class="page-header">作业管理</h1>
    <div class="container study-record">
     <ol class="breadcrumb">
            <li><a href="{% url 'my_courses' %}">我的课程</a></li>
            <li><a href="/student/homework-manage/{{ course_record.class_grade.id }}/">作业管理</a></li>
            <li class="active">作业上交</li>
        </ol>
        <span style="color:indianred;">我的课程</span>
        <span style="color: indianred;" class="pull-right">提交作业</span>
        <hr>
        <div class="form-group row">
            <label class="col-lg-1 ">课程作业:</label>
            <div class="col-lg-8">
                <input type="text" value=" {{ course_record }}" class="form-control" disabled="disabled">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-lg-1" style="width: 100px;">作业内容：</label>
            <div class="col-lg-8">
                <input type="text" value=" {{ course_record.content }}" class="form-control" disabled="disabled">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-lg-2 ">作业内容：</label>
            <div class="col-lg-12 ">
                <textarea cols="30" rows="10" disabled="disabled"
                          class="form-control"> {{ course_record.content }}</textarea>
            </div>
        </div>
        <div>
            <p> 已上传作业列表</p>
            <ul id="student_uploaded">
                {% for uploaded_file in uploaded_files %}
                    <li>{{ uploaded_file }}</li>
                {% endfor %}
            </ul>
        </div>
        <form id="StudentUpload" action="{% url 'homework_file_upload' study_record_id %}" class="dropzone">
            <div style="text-align: center">
                <h1 class="glyphicon glyphicon-book"style="font-size: 60px" ></h1>
                <h4> 请将作业拖放至此处 </h4>
                </div>
                <div class="fallback">
                    <input name="file" type="file" multiple/>
                </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script src="/static/js/dropzone.js"></script>
    <script>
        Dropzone.options.autoDiscover = false;
        Dropzone.options.StudentUpload = {
            paramName: "file", // The name that will be used to transfer the file
            maxFilesize: 3, // MB
            maxFiles: 2,
            parallelUploads: 1,
            addRemoveLinks: true,
            init: function () {
                this.on("success", function (file, response) {
                    var response = JSON.parse(response);
                    if (!response.status) {
                        alert(response.message)
                    } else {
                        $('#student_uploaded').append('<li>' + file.name + '</li>')
                    }
                });
            }
        };

    </script>
{% endblock %}

templates/student/my_class.html
{% extends 'index.html' %}
{% block css %}
    <style>
        .study-record span {
            font-size: 20px;
        }
    </style>
{% endblock %}
{% load student_tags %}
{% block table_content %}
    <h1 class="page-header">我的班级</h1>
    <div class="container study-record">

        <span style="color: chocolate;" class="pull-right">班级列表</span>
        {% for class ,students in students_list.items %}
            <h3 style="color: chocolate"><i class="glyphicon glyphicon-align-left">&nbsp;</i>{{ class }}</h3>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>上课节次</th>
                    <th>联系方式类型</th>
                    <th>联系方式</th>
                    <th>成绩排名</th>
                </tr>
                </thead>
                <tbody>
                {% for student in students %}
                    {% if request.user.userprofile.customer.name == student.customer.name %}
                        <tr style="color: indianred;font-weight: bold">
                    {% endif %}
                    <td>{{ student.customer.name }}</td>
                    <td>{{ student.customer.get_gender_display }}</td>
                    <td>{% get_had_student_class student class %}</td>
                    <td>{{ student.customer.get_contact_type_display }}</td>
                    <td>{{ student.customer.contact }}</td>
                    <td>{% get_score_ranking student class %}</td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
        {% endfor %}


    </div>
{% endblock %}

templates/student/my_courses.html
{% extends 'index.html' %}
{% block css %}
    <style>
        .study-record span {
            font-size: 20px;
        }
    </style>
{% endblock %}
{% load student_tags %}
{% block table_content %}
    <h1 class="page-header">我的课程</h1>
    <div class="container study-record">
        <ol class="breadcrumb">
            <li class="active">我的课程</li>
        </ol>
        <span style="color: indianred;" class="pull-right">课程列表</span>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>课程</th>
                <th>课程类型</th>
                <th>开课时间</th>
                <th>开课总节次</th>
                <th>已上节次</th>
                <th>成绩排名</th>
                <th>作业管理</th>
            </tr>
            </thead>
            <tbody>
            {% for class in class_list %}
                <tr>
                    <td>{{ class }}</td>
                    <td>{{ class.get_class_type_display }}</td>
                    <td>{{ class.start_date }}</td>
                    <td>{{ class.courserecord_set.count }}</td>
                    <td>{% get_had_class class request.user %}</td>
                    <td><a href="/student/my-class/">成绩排名</a></td>
                    <td><a href="/student/homework-manage/{{ class.id }}/">作业管理</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}