CRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sale/', include('sale.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^teacher/', include('teacher.urls')),
    url(r'^kevin-admin/', include('KevinAdmin.urls')),
    url(r'^login/', views.acc_login),
    url(r'^logout/', views.acc_logout, name="logout"),
]

teacher/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as vs

urlpatterns = [
    url(r'^$', vs.teacher_index),
    url(r'^my-class/$', vs.my_class, name='my_class'),
    url(r'^courses-record/(?P<class_id>(\d+))/add/$', vs.add_course_record, name='add_course_record'),
    url(r'^courses-record/(?P<class_id>(\d+))/$', vs.course_record, name='course_record'),
    url(r'^my-class/(?P<class_id>(\d+))/student-list/$', vs.student_list, name='student_list'),
]

database/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)


class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_superuser = True
        user.save(using=self._db)
        return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,

    )
    name = models.CharField(max_length=64, verbose_name="姓名")
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    role = models.ManyToManyField("Role", blank=True, null=True)
    customer = models.OneToOneField('CustomerInfo', blank=True, null=True)
    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):  # __unicode__ on Python 2
        return self.email

    class Meta:
        permissions = (
            ('database_table_list', '可以查看kevinadmin每张表里所有的数据'),
            ('database_table_list_view', '可以访问kevinadmin表里每条数据的修改页'),
            ('database_table_list_change', '可以对kevinadmin表里的每条数据进行修改'),
            ('database_table_obj_add_view', '可以访问kevinadmin每张表的数据增加页'),
            ('database_table_obj_add', '可以对kevinadmin每张表进行数据添加'),
            ('database_table_obj_delete', '可以对kevinadmin每张表进行数据删除'),
            ('database_table_obj_delete_view', '可以对kevinadmin删除时查看所关联的数据'),
             )

        #
        # class UserProfile(models.Model):
        #     """用户信息表"""
        #     user = models.OneToOneField(User)
        #     name = models.CharField(max_length=64, verbose_name="姓名")
        #     role = models.ManyToManyField('Role', blank=True)
        #     customer = models.OneToOneField('CustomerInfo', null=True, blank=True)
        #
        #     def __str__(self):
        #         return self.name


class Role(models.Model):
    """角色表"""
    name = models.CharField(max_length=64, unique=True)
    menus = models.ManyToManyField('Menus')

    def __str__(self):
        return self.name


class CustomerInfo(models.Model):
    """客户信息表"""
    name = models.CharField(max_length=64, default=None)
    contact_type_choices = {
        (0, 'qq'),
        (1, '微信'),
        (2, '手机'),
    }
    contact_type = models.SmallIntegerField(choices=contact_type_choices)
    contact = models.CharField(max_length=64, unique=True)
    source_choices = {
        (0, 'QQ群'),
        (1, '51CTO'),
        (2, '百度推广'),
        (3, '知乎'),
        (4, '转介绍'),
        (5, '其他')
    }
    source = models.SmallIntegerField(choices=source_choices)
    referral_from = models.ForeignKey('self', blank=True, null=True)
    consult_courses = models.ManyToManyField('Course', verbose_name='咨询课程')
    consult_content = models.TextField(verbose_name='咨询描述')
    consultant = models.ForeignKey('UserProfile', verbose_name='课程顾问')
    status_choices = {
        (0, '未报名'),
        (1, '已报名'),
        (2, '已退学')
    }
    id_num = models.CharField(max_length=128, null=True, blank=True)
    emergency_contact = models.PositiveIntegerField(blank=True, null=True)
    status = models.SmallIntegerField(choices=status_choices)
    gender_choices = {(0, '男'), (1, ' 女')}
    gender = models.PositiveIntegerField(blank=True, null=True, choices=gender_choices)
    date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = '客户信息'

    def __str__(self):
        return self.name


class Student(models.Model):
    """学员表"""
    customer = models.OneToOneField("CustomerInfo")
    class_grade = models.ManyToManyField('ClassList')

    def __str__(self):
        return '%s' % self.customer


class CustomerFollowRecord(models.Model):
    """客户跟踪记录表"""
    customer = models.ForeignKey('CustomerInfo')
    content = models.TextField(verbose_name='跟踪内容')
    user = models.ForeignKey('UserProfile', verbose_name='跟进人')
    status_choices = {
        (0, '近期无报名计划'),
        (1, '一个月内报名'),
        (2, '两周内报名'),
        (3, '已报名'),
    }
    status = models.SmallIntegerField(choices=status_choices)
    data = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.content


class Course(models.Model):
    """课程表"""
    name = models.CharField(max_length=64, verbose_name='课程名称', unique=True)
    price = models.PositiveSmallIntegerField()
    period = models.PositiveSmallIntegerField(verbose_name='课程周期(月)', default=5)
    outline = models.TextField(verbose_name='课程大纲')

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """班级列表"""
    branch = models.ForeignKey('Branch')
    course = models.ForeignKey('Course')
    class_type_choices = {
        (0, '脱产'),
        (1, '周末'),
        (2, '网络班'),
    }
    class_type = models.SmallIntegerField(choices=class_type_choices, default=0)
    semester = models.SmallIntegerField(verbose_name='学期')
    contract_template = models.ForeignKey('ContractTemplate', blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name='讲师')
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField('毕业日期', blank=True, null=True)

    class Meta:
        unique_together = ('branch', 'course', 'semester', 'class_type')

    def __str__(self):
        return "{0}({1})".format(self.course.name, self.semester)


class CourseRecord(models.Model):
    """上课记录"""
    class_grade = models.ForeignKey('ClassList', verbose_name='上课班级')
    day_num = models.PositiveSmallIntegerField(verbose_name='课程节次')
    teacher = models.ForeignKey('UserProfile')
    title = models.CharField(max_length=64, verbose_name='本节主题')
    content = models.TextField('本节内容')
    has_homework = models.BooleanField('本节有作业', default=True)
    homework = models.TextField('作业需求', blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('class_grade', 'day_num')

    def __str__(self):
        return "{0}第{1}节".format(self.class_grade, self.day_num)


class StudyRecord(models.Model):
    """学习记录表"""
    course_record = models.ForeignKey('CourseRecord')
    student = models.ForeignKey('Student')
    score_choices = {
        (100, "A+"),
        (90, "A"),
        (85, "B+"),
        (80, "B"),
        (75, "B-"),
        (70, "C+"),
        (60, "C"),
        (40, "C-"),
        (-50, "D"),
        (0, "N/A"),
        (-100, "COPY"),
    }
    score = models.SmallIntegerField(choices=score_choices, default=0)
    show_choices = {
        (0, '缺勤'),
        (1, '已到'),
        (2, '迟到'),
        (3, '早退'),
    }
    show_status = models.SmallIntegerField(choices=show_choices)
    note = models.CharField("成绩备注", blank=True, null=True, max_length=1024)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('course_record', 'student')

    def __str__(self):
        return "{0} {1} {2}".format(self.course_record, self.student, self.score)


class Branch(models.Model):
    """校区"""
    name = models.CharField(max_length=64, unique=True)
    addr = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Menus(models.Model):
    """动态菜单"""
    name = models.CharField(max_length=64)
    url_type_choices = {
        (0, 'absolute'),
        (1, 'dynamic'),
    }
    url_type = models.SmallIntegerField(choices=url_type_choices, default=0)
    url_name = models.CharField(max_length=128)

    class Meta:
        unique_together = ('name', 'url_name')

    def __str__(self):
        return self.name


class ContractTemplate(models.Model):
    """存储合同模板"""
    name = models.CharField(max_length=64)
    content = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.name


class StudentEnrollment(models.Model):
    """学员报名表"""
    customer = models.ForeignKey('CustomerInfo')
    class_grade = models.ForeignKey('ClassList')
    consultant = models.ForeignKey('UserProfile')
    contract_agree = models.BooleanField(default=False)
    contract_signed_date = models.DateTimeField(blank=True, null=True)
    contract_approved = models.BooleanField(default=False)
    contract_approved_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        unique_together = ('customer', 'class_grade')

    def __str__(self):
        return '%s' % self.customer


class PaymentRecord(models.Model):
    """缴费记录表"""
    enrollment = models.ForeignKey('StudentEnrollment')
    payment_type_choices = {
        (0, '报名费'),
        (1, '学费'),
        (2, '退费'),
    }
    payment_type = models.SmallIntegerField(choices=payment_type_choices)
    amount = models.IntegerField('所缴费用', default=500)
    consultant = models.ForeignKey('UserProfile')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.enrollment

teacher/models.py
from django.db import models

# Create your models here.

teacher/views.py
from django.shortcuts import render, redirect, reverse
from database.models import *
from django.contrib.auth.decorators import login_required
from .form import *
from django.db import IntegrityError


def teacher_index(request):
    return redirect(reverse('my_class'))


@login_required()
def my_class(request):
    teacher = request.user
    class_list = ClassList.objects.filter(teachers=teacher)
    return render(request, 'teacher/my_class.html', locals())


@login_required()
def course_record(request, class_id):
    class_grade = ClassList.objects.get(id=class_id)
    record_list = CourseRecord.objects.filter(class_grade__id=class_id, teacher=request.user)
    return render(request, 'teacher/courses_record.html', locals())


@login_required()
def student_list(request, class_id):
    teacher = request.user
    students_list = Student.objects.filter(class_grade=class_id)
    return render(request, 'teacher/student_list.html', locals())


@login_required()
def add_course_record(request, class_id):
    course_record_form = CourseRecordForm()
    if request.method == 'POST':
        course_record_form = CourseRecordForm(data=request.POST)
        if course_record_form.is_valid():
            classes = ClassList.objects.get(id=class_id)
            course_record_form.cleaned_data['class_grade'] = classes
            try:
                CourseRecord.objects.create(**course_record_form.cleaned_data)
                return redirect('/teacher/courses-record/%s/' % class_id)
            except IntegrityError as e:
                unique_error = '本课程本节次已存在'
    return render(request, 'teacher/add_courses_record.html', locals())

templates/teacher/add_courses_record.html
{% extends 'index.html' %}
{% block css %}
    <style>
        .study-record span {
            font-size: 20px;
        }
    </style>
{% endblock %}
{% load teacher_tags %}
{% block table_content %}
    <h1 class="page-header">添加上课记录</h1>
    <div class="container study-record">
        <ol class="breadcrumb">
            <li><a href="{% url 'my_class' %}">我的班级</a></li>
            <li><a href="/teacher/courses-record/{{ class_id }}">上课记录</a></li>
            <li class="active">添加上课记录</li>
        </ol>
        <div class="row">
            <div style="color: #4d764a;" class="col-md-10">
                <h3><i class="glyphicon glyphicon-globe">&nbsp;</i>添加课程记录</h3>
            </div>
            <div class="col-md-2">
                <h4 style="color: indianred;line-height: 58.8px">{{ unique_error }}</h4>
            </div>
        </div>
        <hr>
        <form method="post" class="form-horizontal">
            {% csrf_token %}
            {% for field in course_record_form %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        <p>{{ filed.errors.0 }}</p>
                    </div>
                </div>
            {% endfor %}
            <input type="submit" class="btn btn-primary pull-right" value="创建">
        </form>
    </div>
{% endblock %}

templates/teacher/courses_record.html
{% extends 'index.html' %}
{% block css %}
    <style>
        .study-record span {
            font-size: 20px;
        }
    </style>
{% endblock %}
{% load teacher_tags %}
{% block table_content %}
    <h1 class="page-header">上课记录</h1>
    <div class="container study-record">
        <ol class="breadcrumb">
            <li><a href="{% url 'my_class' %}">我的班级</a></li>
            <li class="active">上课记录</li>
        </ol>
    <div class="row">
        <div style="color: #4d764a;" class="col-md-10">
            <h3><i class="glyphicon glyphicon-globe">&nbsp;</i>{{ class_grade }}</h3>
        </div>
        <div class="col-md-1" style="line-height: 64px;margin-left: 40px">
            <a href="/teacher/courses-record/{{ class_id }}/add/" class="btn btn-success">新建上课记录</a>
        </div>
    </div>
        <hr>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>节次</th>
                <th>上课主题</th>
                <th>本节内容</th>
                <th>本节作业</th>
                <th>上课时间</th>
                <th>布置作业</th>
                <th>更多记录</th>
            </tr>
            </thead>
            <tbody>
            {% for record in record_list %}
                <tr>
                    <td>{{ record.day_num }}</td>
                    <td>{{ record.title }}</td>
                    <td style="width: 300px">{{ record.content }}</td>
                    {% if record.has_homework %}
                        <td>有</td>
                    {% else %}
                        <td>无</td>
                    {% endif %}
                    <td>{{ record.date }}</td>
                    {% if  record.has_homework %}
                        {% if not record.homework %}
                            <td style="width: 300px;"><a href="/student/upload-homework/{{ study_record.id }}">布置作业</a></td>
                        {% else %}
                            <td style="width: 300px;">{{ record.homework }}</td>
                        {% endif %}
                        {% else %}
                        <td style="width: 300px;"></td>
                    {% endif %}
                    <td><a href="">更改记录</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

templates/teacher/my_class.html
{% extends 'index.html' %}
{% block css %}
    <style>
        .study-record span {
            font-size: 20px;
        }
    </style>
{% endblock %}
{% load teacher_tags %}
{% block table_content %}
    <h1 class="page-header">我的班级</h1>
    <div class="container study-record">
        <ol class="breadcrumb">
            <li class="active">我的班级</li>
        </ol>
        <hr>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>班级(学期)</th>
                <th>类型</th>
                <th>开课时间</th>
                <th>开课总节次</th>
                <th>已上节次</th>
                <th>学员数量</th>
                <th>上课记录</th>

            </tr>
            </thead>
            <tbody>
            {% for class in class_list %}
                <tr>
                    <td>{{ class }}</td>
                    <td>{{ class.get_class_type_display }}</td>
                    <td>{{ class.start_date }}</td>
                    <td>{{ class.courserecord_set.count }}</td>
                    <td>{% get_had_class class request.user %}</td>
                    <td><a href="/teacher/my-class/{{ class.id }}/student-list/">{{ class.student_set.count }}</a></td>
                    <td><a href="/teacher/courses-record/{{ class.id }}/">上课记录</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

templates/teacher/student_list.html
{% extends 'index.html' %}
{% block css %}
    <style>
        .study-record span {
            font-size: 20px;
        }
    </style>
{% endblock %}
{% load teacher_tags %}
{% load student_tags %}
{% block table_content %}
    <h1 class="page-header">我的班级</h1>
    <div class="container study-record">
        <ol class="breadcrumb">
            <li><a href="{% url 'my_class' %}">我的班级</a></li>
            <li class="active">班级学员列表</li>
        </ol>
        <hr>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>学员(id)</th>
                <th>联系方式类型</th>
                <th>联系方式</th>
                <th>姓名</th>
                <th>报名日期</th>
                <th>班级排名</th>
                <th>出勤次数</th>
                <th>迟到次数</th>
                <th>缺勤次数</th>
                <th>上课记录</th>
            </tr>
            </thead>
            <tbody>
            {% for student in students_list %}
                <tr>
                    <td>{{ student.id }}</td>
                    <td>{{ student.customer.get_contact_type_display}}</td>
                    <td>{{ student.customer.contact }}</td>
                    <td>{{ student.customer.name }}</td>
                    {% get_approved_date student class_id as approved_date%}
                    <td>{{ approved_date |date   }}</td>
                    <td>{% get_score_ranking student class_id %}</td>
                    <td>{%  get_have_class_time  student  class_id %}</td>
                    <td>{% get_late_time student class_id%}</td>
                    <td>{% get_unable_time student class_id%}</td>
                    <td><a href="/student/upload-homework/{{ study_record.id }}">添加记录</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}